version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    image: YOUR_REGISTRY_HOST:5000/your-namespace/php-mysql-demo:latest
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASS: apppass
    restart: always

volumes:
  db_data:
